### ISSUE TITLE
hook_civicrm_validate drupal_set_message() reports different hook was called

### ISSUE THREAD

**Issue by a-sansom** [eileenmcnaughton/civicrm_developer#3]
The drupal_set_message() message for the hook_civicrm_validate() implementation reports that hook_civicrm_links was called instead of hook_civicrm_validate().

**Comment by eileenmcnaughton** [comment]
Ok I've pushed a fix on this since I already have that module open. I would encourage you to submit pull requests - there are quite a few tidy ups that should ideally be done
