### ISSUE TITLE
License

### ISSUE THREAD

**Issue by laryn** [eileenmcnaughton/civicrm_developer#4]
@eileenmcnaughton What license is this module released under? Can I port it to BackdropCMS as GPL-2.0 or compatible?

**Comment by laryn** [comment]
Or is this actually what I should be using?
https://github.com/fuzionnz/contrib.showallthehooks

**Comment by eileenmcnaughton** [comment]
@laryn I have no idea but happy to have the license you suggest - not so sure about the new one @jitendrapurohit might have comment on that...

**Comment by laryn** [comment]
Thanks @eileenmcnaughton -- as I dig a little deeper, I see that the "Show All The Hooks" extension seems to be a forward iteration of this in a CMS-agnostic way, and I will assume for now that is where future development will go. I submitted a simple PR to make that one fully Backdrop compatible.
https://github.com/fuzionnz/contrib.showallthehooks/issues/10

**Comment by eileenmcnaughton** [comment]
great @laryn @totten FYI^^
